// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"IoCProject/editor"
	"IoCProject/grammar"
	"IoCProject/spelling"
)

// Injectors from wire.go:

func InitializeTextEditor() editor.IoCTextEditor {
	grammarChecker := grammar.NewCloudGrammerChecker()
	spellChecker := spelling.NewCloudSpellChecker()
	ioCTextEditor := editor.NewIocTextEditor(grammarChecker, spellChecker)
	return ioCTextEditor
}
